# Generated by Django 2.1.7 on 2019-10-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enrollment', models.CharField(choices=[('Management', 'Management'), ('Science', 'Science'), ('Humanities', 'Humanities'), ('Edcation', 'Education')], max_length=20)),
                ('year', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], max_length=20)),
                ('fine', models.IntegerField(default=0)),
            ],
        ),
    ]
