# Generated by Django 2.1.7 on 2019-10-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_studentform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentForm',
            new_name='Student',
        ),
    ]
