# Generated by Django 2.1.7 on 2019-10-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_student_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fine',
        ),
    ]
