# Generated by Django 2.1.7 on 2019-10-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_student_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='barcode',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
