# Generated by Django 2.1.7 on 2019-10-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20191026_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='student-barcode'),
        ),
    ]
