# Generated by Django 2.1.7 on 2019-10-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20191029_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='barcode',
        ),
    ]
