# Generated by Django 2.1.7 on 2019-10-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_user_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='std-barcode'),
        ),
    ]
