# Generated by Django 2.1.7 on 2019-10-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
