# Generated by Django 2.1.7 on 2019-12-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20191109_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profile-pic/user.jpg', upload_to='profile-pic'),
        ),
    ]
