# Generated by Django 2.1.7 on 2019-12-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_studentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
