# Generated by Django 2.1.7 on 2019-12-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_studentmodel_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
