# Generated by Django 2.1.7 on 2020-02-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20191227_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.CharField(choices=[('Librarian', 'Librarian'), ('Student', 'Student'), ('Admin', 'Admin')], default='Student', max_length=20),
        ),
    ]
