# Generated by Django 2.1.7 on 2020-02-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_course_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='added_by',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
