# Generated by Django 2.1.7 on 2020-02-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20200211_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Enrollment',
        ),
    ]
