# Generated by Django 2.1.7 on 2019-10-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebooks',
            name='fine',
            field=models.IntegerField(default=0),
        ),
    ]
