# Generated by Django 2.1.7 on 2019-10-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_issuebooks_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbooks',
            name='books_purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='issuebooks',
            name='issued_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
