# Generated by Django 2.1.7 on 2019-10-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_ebooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooks',
            name='book',
            field=models.FileField(upload_to='files'),
        ),
    ]
