# Generated by Django 2.1.7 on 2019-10-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_barcodemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcodemodel',
            name='student',
        ),
        migrations.DeleteModel(
            name='BarCodeModel',
        ),
    ]
