# Generated by Django 2.1.7 on 2019-10-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20191024_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooks',
            name='book',
            field=models.FileField(upload_to=''),
        ),
    ]
