# Generated by Django 2.1.7 on 2019-10-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_auto_20191025_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooks',
            name='book',
            field=models.FileField(upload_to='files'),
        ),
    ]
