# Generated by Django 2.1.7 on 2019-10-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_auto_20191025_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebooks',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ebooks',
            name='allowed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
