# Generated by Django 2.1.7 on 2019-10-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_ebookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookrequest',
            name='action_performed',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
