# Generated by Django 2.1.7 on 2019-10-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_ebookrequest_action_performed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebookrequest',
            name='action_performed',
        ),
    ]
