# Generated by Django 2.1.7 on 2019-10-25 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_remove_ebookrequest_action_performed'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookRequestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('action_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ebooks',
            name='allowed_date',
        ),
        migrations.AddField(
            model_name='ebookrequesthistory',
            name='ebook_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Ebooks'),
        ),
    ]
