# Generated by Django 2.1.7 on 2019-10-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_auto_20191025_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebookrequesthistory',
            name='ebook_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.EbookRequest'),
        ),
    ]
