# Generated by Django 2.1.7 on 2019-10-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_auto_20191025_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebookrequesthistory',
            name='action_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
