# Generated by Django 2.1.7 on 2019-10-26 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_auto_20191025_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebookrequesthistory',
            name='ebook_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.EbookRequest'),
        ),
    ]
