# Generated by Django 2.1.7 on 2019-10-26 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0018_auto_20191026_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebookrequesthistory',
            name='ebook_request',
        ),
        migrations.AddField(
            model_name='ebookrequesthistory',
            name='ebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.Ebooks'),
        ),
        migrations.AddField(
            model_name='ebookrequesthistory',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ebookrequesthistory',
            name='requested_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
