# Generated by Django 2.1.7 on 2019-10-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_auto_20191026_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebooks',
            name='allowed_user',
        ),
        migrations.AddField(
            model_name='ebookrequesthistory',
            name='readable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ebookrequesthistory',
            name='readable_upto',
            field=models.DateTimeField(null=True),
        ),
    ]
