# Generated by Django 2.1.7 on 2019-10-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_auto_20191026_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebookrequesthistory',
            name='readable',
            field=models.BooleanField(),
        ),
    ]
