# Generated by Django 2.1.7 on 2019-10-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_auto_20191026_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebooks',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
