# Generated by Django 2.1.7 on 2019-10-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_ebooks_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=100)),
            ],
        ),
    ]
