# Generated by Django 2.1.7 on 2019-10-27 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_addbooks_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebooks',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.Catagory'),
        ),
    ]
