# Generated by Django 2.1.7 on 2019-10-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_auto_20191028_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbooks',
            name='books_price',
            field=models.CharField(max_length=20),
        ),
    ]
