# Generated by Django 2.1.7 on 2019-10-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0029_auto_20191028_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbooks',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='std-barcode'),
        ),
    ]
