# Generated by Django 2.1.7 on 2019-10-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0030_addbooks_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbooks',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='student-barcode'),
        ),
    ]
