# Generated by Django 2.1.7 on 2019-10-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0032_auto_20191029_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebooks',
            name='barcode',
        ),
        migrations.AlterField(
            model_name='addbooks',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='book-barcode'),
        ),
    ]
