# Generated by Django 2.1.7 on 2019-10-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0034_barcodemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbooks',
            name='barcode',
        ),
    ]
