# Generated by Django 2.1.7 on 2019-10-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0035_remove_addbooks_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcodemodel',
            name='barcode',
        ),
        migrations.AddField(
            model_name='addbooks',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='book-barcode'),
        ),
    ]
