# Generated by Django 2.1.7 on 2019-10-30 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0036_auto_20191029_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyMeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='barcodemodel',
            name='book',
        ),
        migrations.RemoveField(
            model_name='barcodemodel',
            name='student',
        ),
        migrations.AlterField(
            model_name='addbooks',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='BarcodeModel',
        ),
        migrations.AddField(
            model_name='notifymemodel',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.AddBooks'),
        ),
        migrations.AddField(
            model_name='notifymemodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
