# Generated by Django 2.1.7 on 2019-10-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0037_auto_20191030_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
