# Generated by Django 2.1.7 on 2019-10-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0039_auto_20191031_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebooks',
            name='retured_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
