# Generated by Django 2.1.7 on 2019-11-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0043_message_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
