# Generated by Django 2.1.7 on 2019-11-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0044_auto_20191108_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbooks',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='book_barcode'),
        ),
    ]
