# Generated by Django 2.1.7 on 2019-12-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0045_auto_20191116_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbooks',
            name='books_image',
            field=models.ImageField(default='image/bookim.png', upload_to='image'),
        ),
        migrations.AlterField(
            model_name='ebooks',
            name='cover_image',
            field=models.ImageField(default='image/bookim.png', upload_to='image'),
        ),
    ]
