# Generated by Django 2.1.7 on 2019-12-09 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0046_auto_20191205_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebooks',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_by_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
