# Generated by Django 2.1.7 on 2019-12-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0049_auto_20191217_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
