# Generated by Django 2.1.7 on 2019-12-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0050_auto_20191227_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebooks',
            name='renwed',
            field=models.BooleanField(default=False),
        ),
    ]
