# Generated by Django 2.1.7 on 2019-12-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0051_issuebooks_renwed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebooks',
            old_name='renwed',
            new_name='renewed',
        ),
        migrations.AddField(
            model_name='issuebooks',
            name='renewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
