# Generated by Django 2.1.7 on 2019-12-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0052_auto_20191229_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebooks',
            name='new_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
