# Generated by Django 2.1.7 on 2019-12-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0055_remove_issuebooks_new_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifymemodel',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notifymemodel',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notifymemodel',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
