# Generated by Django 2.1.7 on 2020-02-01 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0056_auto_20191229_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catagory',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
