# Generated by Django 2.1.7 on 2020-03-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0058_auto_20200201_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_allowed', models.IntegerField()),
                ('issue_days', models.IntegerField()),
                ('ebook_allowed_days', models.IntegerField()),
            ],
        ),
    ]
