# Generated by Django 2.1.7 on 2020-03-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0059_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='book_allowed',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='settings',
            name='ebook_allowed_days',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='settings',
            name='issue_days',
            field=models.IntegerField(default=30),
        ),
    ]
