# Generated by Django 2.1.7 on 2020-03-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0060_auto_20200313_1127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='AdminSettings',
        ),
    ]
