# Generated by Django 2.1.7 on 2020-03-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0061_auto_20200313_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='fine_amount',
            field=models.IntegerField(default=200),
        ),
    ]
